package com.kodexx.csorm.users;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")

public class UsersFormDesign extends CssLayout{
    protected TextField username;
    protected TextField password;    //might need to change this to  password field
    protected TextField email; //might need to change this to EmailField
    protected TextField firstName;
    protected TextField lastName;
    protected Upload upload;
    protected ProgressBar bar;   
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;
    
    public UsersFormDesign(){
        Design.read(this);
    }
    
}
