/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kodexx.csorm.files;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/**
 *
 * @author kodexx
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
    
public class FilesFormDesign extends CssLayout{
    protected TextField title;
    protected TextField code;  
    protected TextField type;
    protected Label uploadarea;
    protected Button download;
    protected Button view;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;
    
    public FilesFormDesign(){
        Design.read(this);
    }
    
}

/*
public class FilesFormDesign extends CssLayout{
    protected TextField fileName;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;
    
    public FilesFormDesign(){
        Design.read(this);
    }
    
}
*/